### ISSUE TITLE
Fix the POD creation failures when pod configs do not  have AZ or region, or geolocation

### ISSUE THREAD

**Issue by cathyhongzhang** [CentaurusInfra/global-resource-scheduler#262]

**Comment by CoderKevinZhang** [comment]
Availablity Zone doesn't match:
![image](https://user-images.githubusercontent.com/19650434/113770868-89dc8e00-96d7-11eb-8c16-4a6453cf38cc.png)
![image](https://user-images.githubusercontent.com/19650434/113770893-9234c900-96d7-11eb-84c9-90a04726b6df.png)

**Comment by CoderKevinZhang** [comment]
Pod Status is Assigned when availablityZone info is not provided

**Comment by CoderKevinZhang** [comment]
Pod Status is Assigned when geoLocation info is not provided

**Comment by CoderKevinZhang** [comment]
Pod Status is Assigned when regions info is not provided

**Comment by cathyhongzhang** [comment]
will create a PR by 4/14
